// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTCZhYIKbIH4k5-yBl9s9tDJr7zR0Pb6g',
    appId: '1:223676484247:web:ff7c838d1032a861cfb7d2',
    messagingSenderId: '223676484247',
    projectId: 'flutter-chat-app-9d47e',
    authDomain: 'flutter-chat-app-9d47e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-9d47e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMnk0aYXidEV7n8Afo0v_TsloC94rbrzo',
    appId: '1:223676484247:android:a96991a85a3d7007cfb7d2',
    messagingSenderId: '223676484247',
    projectId: 'flutter-chat-app-9d47e',
    storageBucket: 'flutter-chat-app-9d47e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaFppjiSQllA3fdL1DIh1RPvcvImCvoQo',
    appId: '1:223676484247:ios:4d093b300e2c32bccfb7d2',
    messagingSenderId: '223676484247',
    projectId: 'flutter-chat-app-9d47e',
    storageBucket: 'flutter-chat-app-9d47e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaFppjiSQllA3fdL1DIh1RPvcvImCvoQo',
    appId: '1:223676484247:ios:4d093b300e2c32bccfb7d2',
    messagingSenderId: '223676484247',
    projectId: 'flutter-chat-app-9d47e',
    storageBucket: 'flutter-chat-app-9d47e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTCZhYIKbIH4k5-yBl9s9tDJr7zR0Pb6g',
    appId: '1:223676484247:web:df2dbfd2e4a04070cfb7d2',
    messagingSenderId: '223676484247',
    projectId: 'flutter-chat-app-9d47e',
    authDomain: 'flutter-chat-app-9d47e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-9d47e.firebasestorage.app',
  );
}
